<?php

namespace AppBundle\Repository;

/**
 * GastoDoPortadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastoDoPortadorRepository extends \Doctrine\ORM\EntityRepository
{
}
