<?php

namespace AppBundle\Repository;

/**
 * GastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GastoRepository extends \Doctrine\ORM\EntityRepository
{
}
