<?php

namespace AppBundle\Repository;

/**
 * PortadorDoGastoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortadorDoGastoRepository extends \Doctrine\ORM\EntityRepository
{
}
