<?php

namespace AppBundle\Repository;

/**
 * TesteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TesteRepository extends \Doctrine\ORM\EntityRepository
{
}
