<?php

namespace AppBundle\Repository;

/**
 * UnidadeGestoraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadeGestoraRepository extends \Doctrine\ORM\EntityRepository
{
}
